# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3770f93f1c652b4049bc359a4272499d37c9f704bc17b7b92aee5e82706075a32fb0f589e6e9c0839288a99a69546596c6a2960102774844cdb54f7b85f000

test:
  secret_key_base: 5c74d716d319c18ab54e78d997b156f848bb0e8431b0e045979ec994a2e6e2ea64c07a97517d719e4d459e5e10113232c74ffaf06ba541601e5f8d4ce86b7464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
